# üìö Base Workflow - Environment Setup and Command Execution
#
# ‚ö° Overview:
# This workflow serves as a reusable base for other workflows, providing a
# standardized environment to execute custom commands (e.g., `yarn build`, `yarn test`)
# on source code fetched from a specified Git reference.
#
# üöÄ Key Features:
# - üíª Docker-Based Environment Setup: Prepares a Docker environment with OpenSearch Dashboards or Kibana.
# - ‚öôÔ∏è Custom Command Execution: Runs any specified command on the downloaded source code.
# - üì¶ Artifact and Coverage Upload: Uploads build artifacts and test coverage results to GitHub when configured.
#
# üîó Designed for: Easy integration and reuse by other workflows.

name: Base workflow - Environment

on:
  workflow_call:
    inputs:
      reference:
        required: true
        type: string
        default: main
        description: Git reference (branch, tag, or commit SHA) to build from.
      command:
        required: true
        type: string
        default: 'yarn build'
        description: Command to run in the environment.
      docker_run_extra_args:
        type: string
        default: ''
        description: Additional parameters for the docker run command.
        required: false
      artifact_name:
        type: string
        default: ''
        description: Artifact name (will be automatically suffixed with .zip).
        required: false
      artifact_path:
        type: string
        default: ''
        description: Folder to include in the archive.
        required: false
      notify_jest_coverage_summary:
        type: boolean
        default: false
        required: false

jobs:
  # Deploy the plugin in a development environment and run a command
  # using a pre-built Docker image, hosted in Quay.io.
  deploy_and_run_command:
    name: Deploy and run command
    runs-on: ubuntu-24.04
    steps:
      - name: Step 01 - Download the plugin's source code
        uses: actions/checkout@v4
        with:
          repository: wazuh/wazuh-dashboards-reporting
          ref: ${{ inputs.reference }}
          path: wazuh-dashboards-reporting

      # Fix source code ownership so the internal user of the Docker
      # container is also owner.
      - name: Step 02 - Change code ownership
        run: sudo chown 1000:1000 -R wazuh-dashboards-reporting;

      - name: Step 03 - Set up the environment and run the command
        run: |
          # Read the platform version from the package.json file
          echo "Reading the platform version from the package.json...";
          platform_version=$(jq -r '.opensearchDashboards.version | select(. != null)' wazuh-dashboards-reporting/package.json);
          echo "Plugin platform version: $platform_version";

          # Get Wazuh version and concatenate with platform version
          wazuh_version=$(jq -r '.wazuh.version' wazuh-dashboards-reporting/package.json);
          echo "Wazuh version: $wazuh_version";
          
          # Concatenate versions in format: <Opensearch version>-<Wazuh version>
          combined_version="${platform_version}-${wazuh_version}";
          echo "Combined platform version: $combined_version";

          # Up the environment and run the command
          docker run -t --rm \
            -e OPENSEARCH_DASHBOARDS_VERSION=${combined_version} \
            -v `pwd`/wazuh-dashboards-reporting:/home/node/kbn/plugins/wazuh-dashboards-reporting \
            ${{ inputs.docker_run_extra_args }} \
            quay.io/wazuh/osd-dev:${combined_version} \
            bash -c '
              yarn config set registry https://registry.yarnpkg.com;
              cd /home/node/kbn/plugins/wazuh-dashboards-reporting && yarn && ${{ inputs.command }};
            '
      - name: Get the plugin version and and format reference name
        run: |
          echo "githubReference=$(echo ${{ inputs.reference }} | sed 's/\//-/g')" >> $GITHUB_ENV
          echo "version=$(jq -r '.wazuh.version' $(pwd)/wazuh-dashboards-reporting/package.json)" >> $GITHUB_ENV
          echo "revision=$(jq -r '.wazuh.revision' $(pwd)/wazuh-dashboards-reporting/package.json)" >> $GITHUB_ENV

      - name: Step 04 - Upload artifact to GitHub
        if: ${{ inputs.artifact_name && inputs.artifact_path }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}_${{ env.version }}-${{ env.revision }}_${{ env.githubReference }}.zip
          path: ${{ inputs.artifact_path }}
          overwrite: true

      - name: Step 05 - Upload coverage results to GitHub
        if: ${{ inputs.notify_jest_coverage_summary && github.event_name == 'pull_request' }}
        uses: AthleticNet/comment-test-coverage@1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./wazuh-dashboards-reporting/target/test-coverage/coverage-summary.json
          title: 'Code coverage (Jest)'
