name: Test and Build Kibana Reports

on: [pull_request, push]

env:
  PLUGIN_NAME: opendistro_kibana_reports
  OD_VERSION: 1.11.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.9.1
          path: kibana

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.22.0'

      - name: Checkout Plugin
        uses: actions/checkout@v1
        with:
          path: kibana/plugins/${{ env.PLUGIN_NAME }}

      - name: Kibana Plugin Bootstrap
        uses: nick-fields/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: yarn kbn bootstrap

      - name: Test
        uses: nick-fields/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: yarn test --coverage

      - name: Uploads coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Artifact
        run: |
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: kibana-reports
          path: ./build/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}.zip
